version: 2
jobs:
  build:
    working_directory: /connect-it-internal-api
    docker:
      - image: docker:19.03.2-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/connect-it-internal-api.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/connect-it-internal-api.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=connect-it-internal-api -t jubican/connect-it-internal-api:1.0.0 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/connect-it-internal-api.tar jubican/connect-it-internal-api
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/connect-it-internal-api.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push jubican/connect-it-internal-api:1.0.0
            fi
